humbug/urls.py
from django.conf import settings
from django.conf.urls import patterns, url
from django.views.generic import TemplateView, RedirectView
import os.path
import zephyr.forms

# NB: There are several other pieces of code which route requests by URL:
#
#   - runtornado.py has its own URL list for Tornado views.  See the
#     invocation of web.Application in that file.
#
#   - The Nginx config knows which URLs to route to Django or Tornado.
#
#   - Likewise for the local dev server in tools/run-dev.py.

urlpatterns = patterns('',
    url(r'^$', 'zephyr.views.home'),
    url(r'^accounts/login/openid/$', 'django_openid_auth.views.login_begin', name='openid-login'),
    url(r'^accounts/login/openid/done/$', 'zephyr.views.process_openid_login', name='openid-complete'),
    url(r'^accounts/login/openid/done/$', 'django_openid_auth.views.login_complete', name='openid-complete'),
    # We have two entries for accounts/login to allow reverses on the Django
    # view we're wrapping to continue to function.
    url(r'^accounts/login/',  'zephyr.views.login_page',         {'template_name': 'zephyr/login.html'}),
    url(r'^accounts/login/',  'django.contrib.auth.views.login', {'template_name': 'zephyr/login.html'}),
    url(r'^accounts/logout/', 'zephyr.views.logout_then_login'),

    url(r'^accounts/password/reset/$', 'django.contrib.auth.views.password_reset',
        {'post_reset_redirect' : '/accounts/password/reset/done/',
            'template_name': 'zephyr/reset.html',
            'email_template_name': 'registration/password_reset_email.txt',
            }),
    url(r'^accounts/password/reset/done/$', 'django.contrib.auth.views.password_reset_done',
        {'template_name': 'zephyr/reset_emailed.html'}),
    url(r'^accounts/password/reset/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$', 'django.contrib.auth.views.password_reset_confirm',
        {'post_reset_redirect' : '/accounts/password/done/', 'template_name': 'zephyr/reset_confirm.html',
         'set_password_form' : zephyr.forms.LoggingSetPasswordForm}),
    url(r'^accounts/password/done/$', 'django.contrib.auth.views.password_reset_complete',
        {'template_name': 'zephyr/reset_done.html'}),


    url(r'^activity$', 'zephyr.views.get_activity'),

    # Registration views, require a confirmation ID.
    url(r'^accounts/home/', 'zephyr.views.accounts_home'),
    url(r'^accounts/send_confirm/(?P<email>[\S]+)?',
        TemplateView.as_view(template_name='zephyr/accounts_send_confirm.html'), name='send_confirm'),
    url(r'^accounts/register/', 'zephyr.views.accounts_register'),
    url(r'^accounts/do_confirm/(?P<confirmation_key>[\w]+)', 'confirmation.views.confirm'),

    # Portico-styled page used to provide email confirmation of terms acceptance.
    url(r'^accounts/accept_terms/$', 'zephyr.views.accounts_accept_terms'),

    # Terms of service and privacy policy
    url(r'^terms/$',   TemplateView.as_view(template_name='zephyr/terms.html')),
    url(r'^privacy/$', TemplateView.as_view(template_name='zephyr/privacy.html')),

    # "About Humbug" information
    url(r'^what-is-humbug/$', TemplateView.as_view(template_name='zephyr/what-is-humbug.html')),
    url(r'^new-user/$', TemplateView.as_view(template_name='zephyr/new-user.html')),
    url(r'^features/$', TemplateView.as_view(template_name='zephyr/features.html')),

    # Landing page, signup form, and nice register URL
    url(r'^hello/$', TemplateView.as_view(template_name='zephyr/hello.html'),
                                         name='landing-page'),
    url(r'^signup/$', TemplateView.as_view(template_name='zephyr/signup.html'),
                                         name='signup'),
    url(r'^signup/sign-me-up$', 'zephyr.views.beta_signup_submission', name='beta-signup-submission'),
    url(r'^register/$', 'zephyr.views.accounts_home', name='register'),
    url(r'^login/$',  'zephyr.views.login_page', {'template_name': 'zephyr/login.html'}),

    # API and integrations documentation
    url(r'^api/$', TemplateView.as_view(template_name='zephyr/api.html')),
    url(r'^api/endpoints/$', 'zephyr.views.api_endpoint_docs'),
    url(r'^integrations/$', TemplateView.as_view(template_name='zephyr/integrations.html')),
    url(r'^zephyr/$', TemplateView.as_view(template_name='zephyr/zephyr.html')),
    url(r'^apps$', TemplateView.as_view(template_name='zephyr/apps.html')),

    # Job postings
    url(r'^jobs/$', TemplateView.as_view(template_name='zephyr/jobs/index.html')),
    url(r'^jobs/lead-designer/$', TemplateView.as_view(template_name='zephyr/jobs/lead-designer.html')),

    url(r'^robots\.txt$', RedirectView.as_view(url='/static/robots.txt')),
)

urlpatterns += patterns('zephyr.views',
    # These are json format views used by the web client.  They require a logged in browser.
    url(r'^json/update_pointer$',           'json_update_pointer'),
    url(r'^json/get_old_messages$',         'json_get_old_messages'),
    url(r'^json/get_public_streams$',       'json_get_public_streams'),
    url(r'^json/send_message$',             'json_send_message'),
    url(r'^json/invite_users$',             'json_invite_users'),
    url(r'^json/settings/change$',          'json_change_settings'),
    url(r'^json/subscriptions/list$',       'json_list_subscriptions'),
    url(r'^json/subscriptions/remove$',     'json_remove_subscriptions'),
    url(r'^json/subscriptions/add$',        'json_add_subscriptions'),
    url(r'^json/subscriptions/exists$',     'json_stream_exists'),
    url(r'^json/subscriptions/property$',   'json_subscription_property'),
    url(r'^json/get_subscribers$',          'json_get_subscribers'),
    url(r'^json/fetch_api_key$',            'json_fetch_api_key'),
    url(r'^json/get_members$',              'json_get_members'),
    url(r'^json/update_active_status$',     'json_update_active_status'),
    url(r'^json/get_active_statuses$',      'json_get_active_statuses'),
    url(r'^json/tutorial_status$',          'json_tutorial_status'),
    url(r'^json/change_enter_sends$',       'json_change_enter_sends'),
    url(r'^json/get_profile$',              'json_get_profile'),
    url(r'^json/report_error$',             'json_report_error'),
    url(r'^json/update_message_flags$',     'json_update_flags'),
    url(r'^json/register$',                 'json_events_register'),
    url(r'^json/upload_file$',              'json_upload_file'),
    url(r'^json/messages_in_narrow$',       'json_messages_in_narrow'),
    url(r'^json/create_bot$',               'json_create_bot'),
    url(r'^json/get_bots$',                 'json_get_bots'),
    url(r'^json/update_onboarding_steps$',  'json_update_onboarding_steps'),
    url(r'^json/update_message$',           'json_update_message'),
    url(r'^json/fetch_raw_message$',        'json_fetch_raw_message'),

    # These are json format views used by the API.  They require an API key.
    url(r'^api/v1/get_profile$',            'api_get_profile'),
    url(r'^api/v1/get_old_messages$',       'api_get_old_messages'),
    url(r'^api/v1/get_public_streams$',     'api_get_public_streams'),
    url(r'^api/v1/subscriptions/list$',     'api_list_subscriptions'),
    url(r'^api/v1/subscriptions/add$',      'api_add_subscriptions'),
    url(r'^api/v1/subscriptions/remove$',   'api_remove_subscriptions'),
    url(r'^api/v1/get_subscribers$',        'api_get_subscribers'),
    url(r'^api/v1/send_message$',           'api_send_message'),
    url(r'^api/v1/update_pointer$',         'api_update_pointer'),
    url(r'^api/v1/get_members$',            'api_get_members'),

    # This json format view used by the API accepts a username password/pair and returns an API key.
    url(r'^api/v1/fetch_api_key$',          'api_fetch_api_key'),

    # JSON format views used by the redesigned API, accept basic auth username:password.
    # GET returns messages, possibly filtered, POST sends a message
    url(r'^api/v1/messages$', 'rest_dispatch',
            {'GET':  'get_old_messages_backend',
             'PATCH': 'update_message_backend',
             'POST': 'send_message_backend'}),
    url(r'^api/v1/streams$', 'rest_dispatch',
            {'GET':  'get_public_streams_backend'}),
    # GET returns "stream info" (undefined currently?), HEAD returns whether stream exists (200 or 404)
    url(r'^api/v1/streams/(?P<stream_name>.*)/members$', 'rest_dispatch',
            {'GET': 'get_subscribers_backend'}),
    url(r'^api/v1/streams/(?P<stream_name>.*)$', 'rest_dispatch',
            {'HEAD': 'stream_exists_backend',
             'GET': 'stream_exists_backend'}),
    url(r'^api/v1/users$', 'rest_dispatch',
            {'GET': 'get_members_backend'}),
    url(r'^api/v1/users/me$', 'rest_dispatch',
            {'GET': 'get_profile_backend'}),
    url(r'^api/v1/users/me/enter-sends$', 'rest_dispatch',
            {'POST': 'json_change_enter_sends'}),
    url(r'^api/v1/users/me/pointer$', 'rest_dispatch',
            {'GET': 'get_pointer_backend',
             'PUT': 'update_pointer_backend'}),
    # GET lists your streams, POST bulk adds, PATCH bulk modifies/removes
    url(r'^api/v1/users/me/subscriptions$', 'rest_dispatch',
            {'GET': 'list_subscriptions_backend',
             'POST': 'add_subscriptions_backend',
             'PATCH': 'update_subscriptions_backend'}),
    url(r'^api/v1/register$',               'rest_dispatch',
            {'POST': 'api_events_register'}),

    # These are integration-specific web hook callbacks
    url(r'^api/v1/external/beanstalk$',    'api_beanstalk_webhook'),
    url(r'^api/v1/external/github$',        'api_github_landing'),
    url(r'^api/v1/external/jira$',          'api_jira_webhook'),
    url(r'^api/v1/external/pivotal$',       'api_pivotal_webhook'),
)

urlpatterns += patterns('zephyr.tornadoviews',
    # Tornado views
    url(r'^api/v1/get_messages$',           'api_get_messages'),
    url(r'^api/v1/messages/latest$',        'rest_get_messages'),
    url(r'^json/get_updates$',              'json_get_updates'),

zephyr/forms.py
from __future__ import absolute_import

from django import forms
from django.core.exceptions import ValidationError
from django.utils.safestring import mark_safe
from django.contrib.auth.forms import SetPasswordForm

from humbug import settings
from zephyr.models import Realm, get_user_profile_by_email, UserProfile
from zephyr.lib.actions import do_change_password

def is_unique(value):
    try:
        get_user_profile_by_email(value)
        raise ValidationError(u'%s is already registered' % value)
    except UserProfile.DoesNotExist:
        pass

def is_inactive(value):
    try:
        if get_user_profile_by_email(value).is_active:
            raise ValidationError(u'%s is already active' % value)
    except UserProfile.DoesNotExist:
        pass

SIGNUP_STRING = '<a href="https://humbughq.com/signup">Sign up</a> to find out when Humbug is ready for you.'

def has_valid_realm(value):
    try:
        Realm.objects.get(domain=value.split("@")[-1])
    except Realm.DoesNotExist:
        raise ValidationError(mark_safe(u'Registration is not currently available for your domain. ' + SIGNUP_STRING))

def isnt_mit(value):
    if "@mit.edu" in value:
        raise ValidationError(mark_safe(u'Humbug for MIT is by invitation only. ' + SIGNUP_STRING))

class RegistrationForm(forms.Form):
    full_name = forms.CharField(max_length=100)
    password = forms.CharField(widget=forms.PasswordInput, max_length=100)
    terms = forms.BooleanField(required=True)

class ToSForm(forms.Form):
    full_name = forms.CharField(max_length=100)
    terms = forms.BooleanField(required=True)

class HomepageForm(forms.Form):
    # This form is sort of important, because it determines whether users
    # can register for our product. Be careful when modifying the validators.
    if settings.ALLOW_REGISTER:
        email = forms.EmailField()
    else:
        validators = [has_valid_realm, isnt_mit, is_inactive]
        email = forms.EmailField(validators=validators)

class LoggingSetPasswordForm(SetPasswordForm):
    def save(self, commit=True):
        do_change_password(self.user, self.cleaned_data['new_password1'],
                           log=True, commit=commit)
        return self.user

class CreateBotForm(forms.Form):
    full_name = forms.CharField(max_length=100)
    email = forms.EmailField()

templates/zephyr/accounts_accept_terms.html
{% extends "zephyr/portico_signup.html" %}

{% comment %}
Allow the user to accept the terms, creating an email record of that fact.
{% endcomment %}

{% block for_you %}for {% if company_name %} {{company_name}} {% else %} __________ {% endif %} {% endblock %}
{% block portico_content %}

<p>(Welcome! We think you'll like it here.)</p>

<div class="pitch">
    <hr/>
    <p>You're almost there. We just need you to do one last thing.</p>
    <h3>Accept the Humbug terms of service</h3>
</div>

<form method="post" class="form-horizontal" id="registration" action="{% url 'zephyr.views.accounts_accept_terms' %}">
{% csrf_token %}
    <div class="control-group">
        <label for="id_email" class="control-label">Email</label>
        <div class="controls fakecontrol">
            <p>{{ email }}<p>
        </div>
    </div>
    <div class="control-group">
        <label for="id_full_name" class="control-label">Your name</label>
        <div class="controls">
            <input id="id_full_name" class="required" type="text" name="full_name"
                   value="{% if form.full_name.value %}{{ form.full_name.value }}{% endif %}"
                   maxlength="100" />
            {% if form.full_name.errors %}
                {% for error in form.full_name.errors %}
                    <div class="alert alert-error">{{ error }}</div>
                {% endfor %}
            {% endif %}
        </div>
    </div>

    <div class="control-group">
        <div class="controls">
            <label class="checkbox">
                {% comment %}
                This is somewhat subtle.
                Checkboxes have a name and value, and when the checkbox is ticked, the form posts
                with name=value. If the checkbox is unticked, the field just isn't present at all.

                This is distinct from 'checked', which determines whether the checkbox appears
                at all. (So, it's not symmetric to the code above.)
                {% endcomment %}
                <input id="id_terms" class="required" type="checkbox" name="terms"
                       {% if form.terms.value %}checked="checked"{% endif %} />
                I agree to the <a href="/terms">Terms of Service</a>.
            </label>
            {% if form.terms.errors %}
                {% for error in form.terms.errors %}
                    <div class="alert alert-error">{{ error }}</div>
                {% endfor %}
            {% endif %}
        </div>
    </div>
    <br />
    <div class="control-group">
        <div class="controls">
            <input type="submit" class="btn btn-primary" value="Register" /><br />
            <input type="hidden" name="next" value="{{ next }}" />
        </div>
    </div>
</form>

<script type="text/javascript">
autofocus('#id_full_name');
</script>

{% endblock %}

templates/zephyr/api.html
{% extends "zephyr/portico.html" %}

{# API information page #}

{% block portico_content %}
<div class="row-fluid">
  <div class="span8">
    <h1>We hear you like APIs...</h1>
    <ul class="breadcrumb">
      <li><a href="/">Home</a> <span class="divider">/</span></li>
      <li class="active">API</li>
    </ul>

    <p>We have a <a href="/api/endpoints">well-documented API</a> that allows you to build custom integrations, in addition to our <a href="/integrations">existing integrations</a>. For ease-of-use, we've created a Python module that you can drop in to a project to start interacting with our API.</p>
    <br/>
    <a href="https://www.humbughq.com/dist/api/python-humbug_0.1.9.tar.gz" class="btn btn-large btn-primary btn-block"><i class="icon-download icon-white"></i> Download Python bindings and examples</a>
    <span class="pull-right muted">Version 0.1.9</span>

    <p>&nbsp;</p>

    <h3>Installation instructions</h3>
    <p>This package uses distutils, so you can just run <code>python setup.py install</code> after downloading.</p>
    <p>&nbsp;</p>

    <h3>API Keys</h3>
    <p>You can create bots on your <a href="/#settings" target="_blank">settings page</a>.
    Once you have a bot, you can use its email and API key to send messages.</p>

    <p>Create a bot:
    <img class="screenshot" src="/static/images/api/create-bot.png" /></p>

    <p>Look for the bot's email and API key:
    <img class="screenshot" src="/static/images/api/bot-key.png" /></p>

    <p>If you prefer to send messages as your own user, you can also find your API key on your <a href="/#settings" target="_blank">settings page</a>.</p>
    <p>When using our python bindings, you may either specify the user
    and API key for each Client object that you initialize, or let the binding look for
    them in your <code>~/.humbugrc</code>, which you can create as follows:</p>
<div class="codehilite"><pre><span class="k">[api]</span>
<span class="na">key</span><span class="o">=</span><span class="s">BOT_API_KEY</span>
<span class="na">email</span><span class="o">=</span><span class="s">BOT_EMAIL_ADDRESS</span>
</pre></div>

    <p><strong>Don't want to make it yourself?</strong> Humbug <a href="/integrations">already integrates with lots of services</a>.</p>

    <p>&nbsp;</p>

    <h3>Usage examples</h3>
    <ul class="nav nav-tabs" id="api-example-tabs">
      <li class="active"><a href="#curl" data-toggle="tab">curl</a></li>
      <li><a href="#python" data-toggle="tab">Python</a></li>
      <li><a href="#commandline" data-toggle="tab">humbug-send</a></li>
    </ul>

    <div class="tab-content">

      <div class="tab-pane active" id="curl">
        <p>No download required!</p>

{% comment %}
These code snippets are generated using our very own Humbug tool, by
sending them to myself in a code block, and then using the inspector
to pull out the resulting HTML :)
{% endcomment %}

<h4>Stream message</h4>
<div class="codehilite"><pre>curl https://api.humbughq.com/v1/messages <span class="se">\</span>
    -u BOT_EMAIL_ADDRESS:BOT_API_KEY <span class="se">\</span>
    -d <span class="s2">"type=stream"</span> <span class="se">\</span>
    -d <span class="s2">"to=Denmark"</span> <span class="se">\</span>
    -d <span class="s2">"subject=Castle"</span> <span class="se">\</span>
    -d <span class="s2">"content=Something is rotten in the state of Denmark."</span>
</pre></div>

<h4>Private message</h4>
<div class="codehilite"><pre>curl https://api.humbughq.com/v1/messages <span class="se">\</span>
    -u BOT_EMAIL_ADDRESS:BOT_API_KEY <span class="se">\</span>
    -d <span class="s2">"type=private"</span> <span class="se">\</span>
    -d <span class="s2">"to=wdaher@humbughq.com"</span> <span class="se">\</span>
    -d <span class="s2">"content=I come not, friends, to steal away your hearts."</span>
</pre></div>

      </div>

      <div class="tab-pane" id="python">
<div class="codehilite"><pre><span class="c">#!/usr/bin/env python</span>

<span class="kn">import</span> <span class="nn">humbug</span>
<span class="kn">import</span> <span class="nn">sys</span>

<span class="c"># Keyword arguments 'email' and 'api_key' are optional if you are using ~/.humbugrc</span>
<span class="n">client</span> <span class="o">=</span> <span class="n">humbug</span><span class="o">.</span><span class="n">Client</span><span class="p">(</span><span class="p">email</span><span class="o">=</span><span class="s">"othello-bot@example.com"</span><span class="p">,</span>
                       <span class="n">api_key</span><span class="o">=</span><span class="s">"a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5"</span><span class="p">)</span>

<span class="n">stream_message</span> <span class="o">=</span> <span class="p">{</span>
    <span class="s">"type"</span><span class="p">:</span> <span class="s">"stream"</span><span class="p">,</span>
    <span class="s">"to"</span><span class="p">:</span> <span class="s">"Denmark"</span><span class="p">,</span>
    <span class="s">"subject"</span><span class="p">:</span> <span class="s">"Castle"</span><span class="p">,</span>
    <span class="s">"content"</span><span class="p">:</span> <span class="s">"Something is rotten in the state of Denmark."</span>
<span class="p">}</span>

<span class="n">private_message</span> <span class="o">=</span> <span class="p">{</span>
    <span class="s">"type"</span><span class="p">:</span> <span class="s">"private"</span><span class="p">,</span>
    <span class="s">"to"</span><span class="p">:</span> <span class="s">"wdaher@humbughq.com"</span><span class="p">,</span>
    <span class="s">"content"</span><span class="p">:</span> <span class="s">"I come not, friends, to steal away your hearts."</span>
<span class="p">}</span>

<span class="k">print</span> <span class="n">client</span><span class="o">.</span><span class="n">send_message</span><span class="p">(</span><span class="n">stream_message</span><span class="p">)</span>
<span class="k">print</span> <span class="n">client</span><span class="o">.</span><span class="n">send_message</span><span class="p">(</span><span class="n">private_message</span><span class="p">)</span>

<span class="c"># Print each message the user receives</span>
<span class="n">client</span><span class="o">.</span><span class="n">call_on_each_message</span><span class="p">(</span><span class="k">lambda</span> <span class="n">msg</span><span class="p">:</span> <span class="n">sys</span><span class="o">.</span><span class="n">stdout</span><span class="o">.</span><span class="n">write</span><span class="p">(</span><span class="nb">str</span><span class="p">(</span><span class="n">msg</span><span class="p">)</span> <span class="o">+</span> <span class="s">"</span><span class="se">\n</span><span class="s">"</span><span class="p">))</span>
</pre></div>
      </div>


      <div class="tab-pane" id="commandline">
        <p>You can use <code>humbug-send</code> (found in <code>bin/</code> in the tarball) to easily send Humbugs from the command-line, providing the message to be sent on STDIN.

<h4>Stream message</h4>
<div class="codehilite"><pre>humbug-send --stream Denmark --subject Castle \
--user othello-bot@example.com --api-key a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5</pre></div>

<h4>Private message</h4>
<div class="codehilite"><pre>humbug-send wdaher@humbughq.com --user othello-bot@example.com \
--api-key a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5
</pre></div>

<h4>Passing in the message on the command-line</h4>
<p>If you'd like, you can also provide the message on the command-line with the <code>-m</code> flag, as follows:</p>
<div class="codehilite"><pre>humbug-send --stream Denmark --subject Castle \
-m <span class="s2">"Something is rotten in the state of Denmark."</span> \
--user othello-bot@example.com --api-key a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5
</pre></div>

      </div>
      <p>See also the <a href="/api/endpoints">full API endpoint documentation.</a></p>
    </div>
  </div>
</div>

{% endblock %}

templates/zephyr/compose.html
<div class="row-fluid">
  <div class="span12" id="compose">
    <div id="compose_controls">
          <div id="compose_buttons">
            <span class="new_message_button">
              <button type="button" class="btn btn-large compose_stream_button"
                      id="left_bar_compose_stream_button_big" title="New stream message (c)">
                <i class="icon-vector-bullhorn"></i><span class="compose_stream_button_label">&nbsp;&nbsp;New stream message</span>
              </button>
            </span>
            <span class="new_message_button">
              <button type="button" class="btn btn-large compose_private_button"
                      id="left_bar_compose_private_button_big" title="New private message (C)">
                <i class="icon-vector-user"></i><span class="compose_private_button_label">&nbsp;&nbsp;New private message</span>
              </button>
            </span>
          </div>
    </div>
    <div class="message_comp">
      <button type="button" class="close" id='compose_close'>×</button>
      <div class="alert" id="send-status">
        <span class="send-status-close">&times;</span>
        <span id="error-msg"></span>
      </div>
      <form id="send_message_form" action="/json/send_message" method="post">
        {% csrf_token %}
        <table class="compose_table">
          <tbody>
            <tr class="ztable_layout_row">
              <td class="ztable_comp_col1" />
              <td class="ztable_comp_col2" />
            </tr>
            <tr id="stream-message">
              <td class="message_header message_header_stream left_part">
              </td>
              <td class="message_header message_header_stream right_part">
                  <span id="compose-lock-icon">
                    <i class="icon-lock" title="This is an invite-only stream"></i>
                  </span>
                  <input type="text" class="recipient_box" name="stream" id="stream"
                         maxlength="30"
                         value="" placeholder="Stream" autocomplete="off" tabindex="120"/>
                  <i class="icon-vector-narrow icon-vector-small"></i>
                  <input type="text" class="recipient_box" name="subject" id="subject"
                         maxlength="60"
                         value="" placeholder="Subject" autocomplete="off" tabindex="130"/>
              </td>
            </tr>
            <tr id="private-message">
              <td class="message_header_private_message message_header left_part"></td>
              <td class="message_header_private_message message_header right_part dark_background">
                You and <input type="text" class="recipient_box" name="recipient" id="private_message_recipient"
                               value="" placeholder="one or more people..." autocomplete="off" tabindex="130"/>
              </td>
            </tr>
            <tr>
              <td id="left-of-compose">
                <div>
                  <input type="file" id="file_input" class="notvisible pull-left" multiple />
                  <a class="message-control-button icon-vector-paper-clip notdisplayed"
                     id="attach_files" href="#" title="Attach files"></a><br />
                  <a class="message-control-button icon-vector-font"
                     href="#markdown-help" title="Formatting" data-toggle="modal"></a>
                </div>
              </td>
              <td class="messagebox">
                <div class="message_content">
                  <textarea class="new_message_textarea" name="content" id="new_message_content"
                            value="" placeholder="Compose your message here..." tabindex="140" maxlength="10000"></textarea>
                  <div id="send_controls">
                    <input type="submit" value="Send" id="compose-send-button" class="btn btn-primary send_message" tabindex="150"/>
                  </div>
                </div>
                <div id="below-compose-content">
                  <a id="restore-draft" onclick="compose.restore_message();">Restore last draft?</a>
                  <span id="sending-indicator">Sending...</span>
                  <input type="checkbox" class="pull-right" id="enter_sends" name="enter_sends" value="ender_sends" />
                  <label id="enter-sends-label" class="pull-right" for="enter_sends">Press Enter to send&nbsp;</label>
                </div>
              </td>
            </tr>
          </tbody>
        </table>
      </form>
    </div>
  </div>
</div>

templates/zephyr/reset_done.html
{% extends "zephyr/portico_signup.html" %}

{% block portico_content %}

<div class="pitch">
    <hr/>
    <h3>Password changed.</h3>
</div>
<p>Done! You can now <a href="{% url 'django.contrib.auth.views.login' %}">log in</a>.</p>

{% endblock %}

templates/zephyr/reset_emailed.html
{% extends "zephyr/portico_signup.html" %}

{% block portico_content %}

<p>Check your email to continue the password reset process.</p>

{% endblock %}

templates/zephyr/subscriptions.html
{# Subscriptions management tab of the app. #}

<div class="row-fluid">
  <div class="span12">
    <div class="subscriptions">
      <h1>Streams</h1>
      <div class="alert" id="subscriptions-status"></div>
      <div id="subs_page_loading_indicator"></div>
      <table class="table table-condensed table-striped">
        <tbody id="subscriptions_table">
          <tr id="create_stream_row"><td>
              <div class="subscription_table_elem">
                <form id="add_new_subscription" class="form-inline">
                  <input type="text" name="stream_name" id="create_stream_name"
                         placeholder="Stream name" value="" />
                  <input type="submit" class="btn btn-primary"
                         id="create_stream_button" value="Create stream" />
                </form>
              </div>
          </td></tr>
        </tbody>
      </table>
    </div>
  </div>
</div>

{% include "zephyr/stream_creation_prompt.html" %}